#kubectl create secret docker-registry regcred --docker-server=ghcr.io --docker-username=<your-username> --docker-password=<your-pword/access token> --docker-email=<your-email>
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: learning
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic2dydGhhdGkiLCJwYXNzd29yZCI6ImdocF90UHI4UFVjbGJPTzBrakJqamJtUE4xMzkxa3hEWnozT2ZEdlkiLCJlbWFpbCI6InNncnRoYXRpQGdtYWlsLmNvbSIsImF1dGgiOiJjMmR5ZEdoaGRHazZaMmh3WDNSUWNqaFFWV05zWWs5UE1HdHFRbXBxWW0xUVRqRXpPVEZyZUVSYWVqTlBaa1IyV1E9PSJ9fX0=
