apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-pvc2
  namespace: learning
spec:
  accessModes:
    - ReadWriteMany #option: ReadWriteMany, ReadWriteOnce, ReadOnlyMany
  storageClassName: azure-file
  resources:
    requests:
      storage: 100Gi
