apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file
  namespace: learning
provisioner: file.csi.azure.com # options: kubernetes.io/azure-disk, kubernetes.io/azure-file,
parameters:
  skuName: Premium_LRS # options: Standard_LRS, Premium_LRS, StandardSSD_LRS
  location: centralindia # specify your location if needed
reclaimPolicy: Delete # options: Retain, Delete, Recycle
volumeBindingMode: Immediate # options: Immediate, WaitForFirstConsumer
