apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "azure-jwt-authpolicy"
  namespace: learning
spec:
  selector:
    matchLabels:
      app: helloworld #update lables
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
