openapi: 3.0.0
info:
  title: Region
  description: A free fake online REST API for testing and prototyping.
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /region:
    get:
      summary: region
      responses:
        '200':
          description: region
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    type: string
                    example: ap-south-1
              examples:
                region: ap-south-1