apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-auth"
  namespace: learning
spec:
  selector:
    matchLabels:
      app: helloworld
  jwtRules:
  - issuer: "issuer"
    jwks: |
        {
          "keys": [ 
            { #copy generated JWK in below lines#
            "e": "AQAB",
            "kid": "y-xkKzYdRNCMZGssrVUeTJHFpJatJaihaAE3iYFROCE",
            "kty": "RSA",
            "n": "vRKeZEQcwG-zqdn_sDyT_C4T1-TBc8IcLPFuc5FhMENyqhywPklEfj6VlTgFOnkVM2DBkfEnmtvs2aDHTejFt3m4jDcRwE4Lc3roL3QDi09xw52AhfdfK_KeL5yPyQuBds_LDnpEbI3_I0ZfkEpWAT8nv3H7-NZ3O2p4simUtEMSlu3MHdriIBWIjoxDbIvHpSeDSorpDfgDt2wC_w-fT3PDFDP724IcjwrLcnQgVa5Ir2dc7lBF9lS8WIbB8ZT15vKQQGY6XP9pP7LfabXXQhZdqU3kqpAzp5bkfwFxOum5Yk-IzvXlm8gHxjs2_un-_OC3pMPzU40vhv53JyHXIQ"
            } 
          ]
        }   