apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: learning
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: helloworld