#secret
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: learning
type: Opaque #option: "kubernetes.io/tls", "kubernetes.io/dockerconfigjson" 
data:
  username: dGVzdA== # base64 encoded ex: echo -n "admin" | base64
  password: cGFzc3dvcmQ= # base64 encoded
