controller:
  replicaCount: 2
  nodeSelector:
    "kubernetes.io/os": linux
  admissionWebhooks:
    patch:
      nodeSelector:
        "kubernetes.io/os": linux
  service:
    annotations:
      "service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path": /healthz
    externalTrafficPolicy: Local
defaultBackend:
  nodeSelector:
    "kubernetes.io/os": linux
controller.config:
  log-format-escape-json: "false"
  log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
  error-log-level: info