apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  namespace: daemonset
  labels:
    app: fluentd
spec:
  selector:
    app: fluentd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 24224