apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: daemonset
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd.pos
      tag kube.*
      format json
    </source>

    <source>
      @type prometheus
      port 24231
      <metric>
        name fluentd_input_status
        type counter
        labels
          tag
      </metric>
    </source>
    