namespace: grafana
service:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc.cluster.local:80
        isDefault: true
