openapi: 3.0.0
info:
  title: AWS API
  description: A free fake online REST API for testing and prototyping.
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      summary: Get all posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Internal server error
    delete:
      summary: Get all posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Internal server error
  /posts/{id}:
    get:
      summary: Get a post by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the post to retrieve
      responses:
        '200':
          description: A single post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
        '500':
          description: Internal server error
components:
  schemas:
    Post:
      type: object
      properties:
        userId:
          type: integer
          description: The ID of the user who created the post
        id:
          type: integer
          description: The unique ID of the post
        title:
          type: string
          description: The title of the post
        body:
          type: string
          description: The body content of the post
