apiVersion: v1
kind: Service
metadata:
  name: helloworld-v2
  namespace: learning
  labels:
    app: helloworld
    service: helloworld
spec:
  selector:
    app: helloworld
    version: v2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

