apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-pvc
  namespace: learning
spec:
  accessModes:
    - ReadWriteOnce #option: ReadWriteMany, ReadWriteOnce, ReadOnlyMany
  storageClassName: azure-disk
  resources:
    requests:
      storage: 1Gi
