namespace: grafana
service:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
#persistence volume
# persistence:
#   enabled: true
#   storageClassName: azure-disk  # Set this to your Azure Disk StorageClass name
#   accessModes:
#     - ReadWriteOnce
#   size: 10Gi  # Set your desired storage size
#adding prometheus datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc.cluster.local:80
        isDefault: true
#grafana configuration
grafana.ini:
  paths:
    data: /var/lib/grafana/data
  log:
    mode: console
  database:
    type: sqlite3
    path: grafana.db
#autoload dashboards
sidecar:
  dashboards:
    enabled: true
    folder: /var/lib/grafana/dashboards/default
    searchNamespace: ALL
    label: grafana_dashboard
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      allowUiUpdates: true
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    k8s:
      file: dashboards/6417_rev1.json
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus

